# Generated by Django 4.2.2 on 2023-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_categoryarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('A', 'статья'), ('N', 'новость')], default='N', max_length=1),
        ),
    ]
